import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import 'bulma/css/bulma.min.css';
import './style.css';
import {api,date,money,enablePush,disablePush} from './api.js';
import ReservationForm from './ReservationForm.jsx';
import BoardingView from './BoardingView.jsx';
import POS from './POS.jsx';
import Operations from './Operations.jsx';
import Admin from './Admin.jsx';
function Auth({onUser}){
 const [register,setRegister]=useState(false),[values,setValues]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [notice,setNotice]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);try{onUser(await api(`/auth/${register?'register':'login'}`,{method:'POST',body:values}));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <form className="box auth-box" onSubmit={submit}><h2 className="title is-4">{register?'Crea tu cuenta':'Bienvenido de nuevo'}</h2>{(register?['name','phone','email','password']:['email','password']).map(key=><label className="field is-block" key={key}>{({name:'Nombre',phone:'Teléfono',email:'Correo',password:'Contraseña (mínimo 12 caracteres)'})[key]}<input className="input mt-1" required type={key==='password'?'password':key==='email'?'email':key==='phone'?'tel':'text'} minLength={key==='password'?12:undefined} maxLength={key==='password'?72:120} autoComplete={key==='password'?(register?'new-password':'current-password'):key==='name'?'name':key==='phone'?'tel':'email'} value={values[key]||''} onChange={e=>setValues({...values,[key]:e.target.value})}/></label>)}{error&&<p role="alert" className="notification is-danger is-light">{error}</p>}{notice&&<p role="status" className="notification">{notice}</p>}<button disabled={busy} className={`button is-primary is-fullwidth ${busy?'is-loading':''}`}>{register?'Registrarme':'Entrar'}</button><button className="button is-text mt-3" type="button" onClick={()=>{setRegister(!register);setValues({});setError('');}}>{register?'Ya tengo cuenta':'Crear una cuenta'}</button>{!register&&<button type="button" className="button is-text" onClick={async()=>{try{setNotice((await api('/auth/recover',{method:'POST',body:{email:values.email}})).message);}catch(e){setError(e.message);}}}>Recuperar acceso</button>}</form>;
}
function Activate({token,onUser}){const [password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <form className="box auth-box" onSubmit={async e=>{e.preventDefault();setBusy(true);try{onUser(await api('/auth/activate',{method:'POST',body:{token,password}}));history.replaceState(null,'','/');}catch(e){setError(e.message);}finally{setBusy(false);}}}><h1 className="title is-4">Establece tu contraseña</h1><label className="label">Mínimo 12 caracteres</label><input className="input" type="password" autoComplete="new-password" minLength="12" maxLength="72" required value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="notification is-danger is-light mt-3">{error}</p>}<button disabled={busy} className="button is-primary mt-4">Guardar y entrar</button></form>;}
function MyBookings(){const [rows,setRows]=useState([]),[error,setError]=useState('');useEffect(()=>{api('/bookings').then(setRows).catch(e=>setError(e.message));},[]);return <div className="box"><h1 className="title">Mis reservas</h1>{error&&<p>{error}</p>}{rows.map(b=><a className="fare-row" href={`/ticket/${b.ticket_token}`} key={b.id}><span>{date(b.created_at)}<small>{b.passengers} pasajeros · {b.status}</small></span><strong>{money(b.total_cents)}</strong></a>)}{!rows.length&&!error&&<p>Aún no tienes reservas.</p>}</div>;}
function App(){
 const [user,setUser]=useState(null),[loaded,setLoaded]=useState(false),[tab,setTab]=useState('reserve'),[message,setMessage]=useState('');
 useEffect(()=>{api('/auth/me').then(setUser).catch(()=>{}).finally(()=>setLoaded(true));if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});},[]);
 const match=location.pathname.match(/^\/(ticket|vehicle|tracking)\/([a-f0-9-]+)$/i);
 const activation=location.pathname.match(/^\/activate\/([a-f0-9]{64})$/);
 const requiresAuth=match?.[1]==='ticket';
 return <><header className="site-header"><a className="brand" href="/">Conexion<span>ES</span><small>APATZINGÁN ↔ MORELIA</small></a><div className="header-actions">{user?<><span>{user.name}</span><button className="button is-small" onClick={async()=>{try{await disablePush();await api('/auth/logout',{method:'POST'});setUser(null);setTab('reserve');}catch(e){setMessage(e.message);}}}>Salir</button></>:<button className="button is-small" onClick={()=>setTab('login')}>Ingresar</button>}</div></header>
 {!match&&tab==='reserve'&&<section className="hero-banner"><div><p className="eyebrow">CERCA DE LO QUE IMPORTA</p><h1>Un camino.<br/>Muchas conexiones.</h1><p>De Apatzingán a Morelia y de regreso.<br/>Tu familia, tu salud y tu siguiente viaje, más cerca.</p><div className="hero-tags"><span>Rutas interurbanas</span><span>Aeropuerto</span><span>CREE / Teletón</span></div></div><div className="route-art" aria-hidden="true"><div className="route-line"></div><span className="route-stop first">Apatzingán</span><span className="route-stop last">Morelia</span><div className="van">C<span>→</span></div></div></section>}
 <main className="page-container">{user&&!match&&<nav className="tabs"><ul>{[['reserve','Reservar'],['bookings','Mis reservas'],...(['admin','cashier'].includes(user.role)?[['pos','Taquilla']]:[]),...(['admin','driver'].includes(user.role)?[['operations','Operación']]:[]),...(user.role==='admin'?[['admin','Administración']]:[])].map(([id,label])=><li key={id} className={tab===id?'is-active':''}><a onClick={()=>setTab(id)}>{label}</a></li>)}</ul><button className="button is-small" onClick={async()=>{try{await enablePush();setMessage('Notificaciones activadas.');}catch(e){setMessage(e.message);}}}>Activar avisos</button></nav>}
 {message&&<p className="notification" role="status">{message}<button aria-label="Cerrar aviso" className="delete" onClick={()=>setMessage('')}/></p>}
 {!loaded?<p>Cargando…</p>:activation?<Activate token={activation[1]} onUser={u=>{history.replaceState(null,'','/');setUser(u);}}/>:match?(requiresAuth&&!user?<Auth onUser={setUser}/>:<BoardingView mode={match[1]} token={match[2]} user={user}/>):tab==='login'&&!user?<Auth onUser={u=>{setUser(u);setTab('reserve');}}/>:tab==='pos'&&user?<POS user={user}/>:tab==='operations'&&user?<Operations/>:tab==='admin'&&user?<Admin/>:tab==='bookings'&&user?<MyBookings/>:<><div className="section-heading"><h2>Tu próximo destino</h2><span>Lugares, sin complicaciones</span></div><ReservationForm user={user}/>{!user&&<Auth onUser={setUser}/>}</>}
 </main><footer>ConexionES · Viajes que acercan <span>Apátzingán / Morelia / Aeropuerto / Rutas médicas</span></footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
