import {useEffect,useState} from 'react';
import {api,date} from './api.js';
export default function Operations(){
 const [data,setData]=useState(null),[trips,setTrips]=useState([]),[fleet,setFleet]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const [d,t]=await Promise.all([api('/local/jobs'),api('/operations/trips')]);setData(d);setTrips(t);}catch(e){setError(e.message);}}
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer);},[]);
 async function act(path,body,method='POST'){setBusy(true);try{await api(path,{method,body});await load();setError('');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><h1 className="title">Operación de viajes</h1>{error&&<p role="alert" className="notification is-danger is-light">{error}</p>}<div className="box"><h2 className="title is-4">Mis salidas interurbanas</h2>{trips.map(t=><div className="fare-row" key={t.id}><span>{t.origin} → {t.destination}<small>{date(t.departure_at)} · {t.status}</small></span>{['scheduled','boarding','en_route'].includes(t.status)&&<button disabled={busy} className="button is-primary is-small" onClick={()=>act(`/trips/${t.id}/status`,{status:{scheduled:'boarding',boarding:'en_route',en_route:'arrived'}[t.status]},'PATCH')}>{({scheduled:'Iniciar abordaje',boarding:'Salir a ruta',en_route:'Registrar llegada'})[t.status]}</button>}</div>)}{trips.length===0&&<p>No hay salidas asignadas.</p>}</div>
 <div className="box"><h2 className="title is-4">Viaje Rápido</h2><div className="select mb-4"><select value={fleet} onChange={e=>setFleet(e.target.value)}><option value="">Elige tu auto</option>{data?.fleet.map(f=><option key={f.id} value={f.id}>{f.model} · {f.plate} · {f.city}</option>)}</select></div>{data?.jobs.map(j=><div className="fare-row" key={j.id}><span><strong>{j.zone}</strong><small>{j.destination} · Llegada {date(j.arrival_at)}<br/>{j.passengers} pasajeros · {j.luggage} maletas · {j.status}</small></span>{j.status==='waiting'&&<button disabled={!fleet||busy} className="button is-primary" onClick={()=>act(`/local/jobs/${j.id}/accept`,{fleetId:fleet})}>Aceptar</button>}{j.status==='accepted'&&<button disabled={busy} className="button" onClick={()=>act(`/local/jobs/${j.id}/complete`,{})}>Completar</button>}</div>)}</div></>;
}
